spring:
  application:
    name: msg-service
  datasource:
    url: #
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  rabbitmq:
    host: #
    port: 5672
    username: aiding
    password: aiding
    publisher-confirms: true
    virtual-host: /
  redis:
    host: #
    port: 6379
    password: null
    timeout: 0
    pool:
      max-active: 8
      max-wait: 0
      max-idle: 8
      min-idle: 0
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config: classpath:config/mybatis-config.xml
  type-aliases-package: com.edudigital.cloudy.amp.msg.service.entity.po
server:
  port: 8202
eureka:
  client:
    serviceUrl:
      defaultZone: #
    healthcheck:
      enabled: false
  instance:
    preferIpAddress: true
    ip-address: #
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /msg-service/msg/info
    healthCheckUrlPath: /msg-service/health
amp:
  msg:
    ali:
      product: #
      domain: #
      region: #
      accesskeyid: #
      accesskeysecret: #
      signname: #
logging:
  level:
    org:
      springframework:
        amqp: ERROR
    com:
      patterncat: INFO