spring:
  application:
    name: file-service
  datasource:
    url: #
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  data: 
    mongodb: 
      uri: #
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#mybatis:
#  mapper-locations: classpath*:mappers/*Mapper.xml
#  config: classpath:config/mybatis-config.xml
#  type-aliases-package: com.edudigital.cloudy.amp.news.entity.po
tb:
  static:
    file:
      dir: /usr/local/uploadfiles/amp/tb/

     
server:
  port: 8201

eureka:
  client:
    serviceUrl:
      defaultZone: #
    healthcheck:
      enabled: false
  instance:
    leaseRenewalIntervalInSeconds: 1  
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /file-service/info
    healthCheckUrlPath: /file-service/health
    preferIpAddress: true
    ip-address: #
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
 
      
     
    