server:
  port: 8752
spring:
  application:
    name: registration-center-bk
eureka:
  instance:
    hostname: registration-center-bk
    preferIpAddress: true
    ip-address: 192.168.1.236
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.236:8751/registration-center/eureka/
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false