server:
  port: 8101
spring:
  application:
    name: registration-center
eureka:
  instance:
    hostname: registration-center
    preferIpAddress: true
    ip-address: #
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: #
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false