eureka:
  client:
    serviceUrl:
      defaultZone: http://47.97.23.45:8101/registration-center/eureka/,http://47.97.23.45:8102/registration-center/eureka/
    healthcheck:
      enabled: false
  instance:
    preferIpAddress: true
    ip-address: 47.97.23.45
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /textbook-service/swagger-ui.html
    healthCheckUrlPath: /textbook-service/health
server:
  port: 8301
spring:
  application:
    name: textbook-service
  datasource:
    url: jdbc:mysql://120.26.164.209:3306/amp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 120.26.164.209
    port: 5672
    username: aiding
    password: aiding
    virtual-host: /
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config: classpath:config/mybatis-config.xml
  type-aliases-package: com.edudigital.cloudy.amp.textbook.service.entity.po
tb:
  static:
    file:
      dir: /usr/local/uploadfiles/tb/
      type: .zip
file:
  path: /usr/local/uploadfiles/tb/