eureka:
  client:
    serviceUrl:
      defaultZone: http://registration-center:8751/registration-center/eureka/,http://registration-center-bk:8752/registration-center/eureka/
    healthcheck:
      enabled: false
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /textbook-service/swagger-ui.html
    healthCheckUrlPath: /textbook-service/health
server:
  port: 8765
spring:
  application:
    name: textbook-service2
  datasource:
    url: jdbc:mysql://192.168.1.236:3306/amp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.236
    port: 5672
    username: aiding
    password: aiding
    virtual-host: /
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config: classpath:config/mybatis-config.xml
  type-aliases-package: com.edudigital.cloudy.biz.ebk.entity.dos
tb:
  static:
    file:
      dir: /usr/local/uploadfiles/ebk/
      type: .zip
file:
  path: F:/file/