eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.236:8111/registration-center/eureka/
    healthcheck:
      enabled: false
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /news-custom/info
    healthCheckUrlPath: /news-custom/health
server:
  port: 8333
spring:
  application:
    name: news-custom