spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.1.236:3306/amp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.236
    port: 5672
    username: aiding
    password: aiding
    virtual-host: /
  data:
    mongodb:
      uri: mongodb://192.168.1.236:27017/order
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config: classpath:config/mybatis-config.xml
  type-aliases-package: com.edudigital.cloudy.amp.order.service.entity.po
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://registration-center:8751/registration-center/eureka/,http://registration-center-bk:8752/registration-center/eureka/
    healthcheck:
      enabled: false
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /news-service/info
    healthCheckUrlPath: /news-service/health
amp:
  pay:
    ali:
      notify_url: #
    wx:
      notify_url: #
      appid: #
      mchid: #
logging:
  level: 
    com.ibatis: DEBUG
  