spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://120.26.164.209:3306/amp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 120.26.164.209
    port: 5672
    username: aiding
    password: aiding
    virtual-host: /
#  data:
#    mongodb:
#      uri: mongodb://47.97.23.45:27017/order
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config: classpath:config/mybatis-config.xml
  type-aliases-package: com.edudigital.cloudy.amp.order.service.entity.po
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.97.23.45:8101/registration-center/eureka/,http://47.97.23.45:8102/registration-center/eureka/
    healthcheck:
      enabled: false
  instance:
    preferIpAddress: true
    ip-address: 47.97.23.45
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /news-service/info
    healthCheckUrlPath: /news-service/health
amp:
  pay:
    ali:
      notify_url: http://47.97.23.45:8888/order-service/notify/pay/ali
    wx:
      notify_url: http://47.97.23.45:8888/order-service/notify/pay/wx
      appid: wx7230f7742993d161
      mchid: 1269929101
  