spring:
  application:
    name: order-service
  datasource:
    url: #
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: #
    port: 5672
    username: aiding
    password: aiding
    virtual-host: /
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config: classpath:config/mybatis-config.xml
  type-aliases-package: com.edudigital.cloudy.amp.order.service.entity.po
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: #
    healthcheck:
      enabled: false
  instance:
    preferIpAddress: true
    ip-address: #
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: /news-service/info
    healthCheckUrlPath: /news-service/health
amp:
  pay:
    ali:
      notify_url: #
    wx:
      notify_url: #
      appid: #
      mchid: #
  